apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app1
  labels:
    app.kubernetes.io/name: gitops-demo-app1
    app.kubernetes.io/instance: gitops-demo-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gitops-demo-app1
      app.kubernetes.io/instance: gitops-demo-app1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitops-demo-app1
        app.kubernetes.io/instance: gitops-demo-app1
    spec:
      containers:
        - name: gitops-demo-app1
          image: "c8n.io/myspotontheweb/gitops-demo-app1:main"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
